### PR TITLE
Fix "A generic class can't have static fields" error when a subclass of Parser is used inside a macro

### PR DESCRIPTION
**Pull request by joshtynjala**

### CODE REVIEW

**Comment by Simn** [comment]
That doesn't seem right. Fencing a macro function like this should mean that the macro can't find its implementation...

**Comment by joshtynjala** [comment]
@Simn But you can't use macros inside macros, right? So it should be hidden.

**Comment by joshtynjala** [comment]
Or maybe the `static public macro function parse()` simply needs to be moved to a different class other than `Parser` so that subclasses of `Parser` can be used inside a macro.

Obviously, if I'm using a `Parser` subclass in a macro, then I won't be able to take advantage of the automatic rewriting of `switch stream` and the case matching, but doing that manually was relatively easy. Similarly, I had to avoid the automatic `@:rule` building for my `Lexer`, but it was easy to switch to `Lexer.buildRuleset` instead.

**Comment by Simn** [comment]
There are two versions of a `macro` function:

1. The "outside" version which is visible to the current target, which is basically just the function declaration.
2. The actual implementation, which is what the macro executes.

Fencing like this would mean that there is no implementation in the macro context, which should lead to some sort of error.

**Comment by joshtynjala** [comment]
Thanks for the explanation. Well, if my PR isn't the correct solution, then I'll just create a new issue instead. It's still something that needs improvement either way.

**Pull request closed without merging**
